version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - errorlint
    - contextcheck
    - noctx
    - bodyclose
    - gosec
    - revive
    - misspell
    - unconvert
    - prealloc
  exclusions:
    rules:
      - linters:
          - revive
        text: "^(package-comments|exported):"


formatters:
  enable:
    - gofmt
    - goimports
